# Generated by Django 3.2.1 on 2021-05-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0003_game_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
