# Generated by Django 3.2.1 on 2021-05-13 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0005_gamepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepicture',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
